=== Amitpatil215/JIIT-SEM-6/CloudBasedEnterpriseSystem/T2_practice/spacestation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://amitpatil/spacestaion",
    "title": "Spacestaion Schema",
    "description": "Describes space station",
    "properties": {
        "name": {
            "type": "string",
            "minLength": 3,
            "maxLength": 20
        },
        "population": {
            "type": "integer",
            "description": "Current no of people in place station",
            "exclusiveMinimum": 5,
            "exclusiveMaximum": 1000
        },
        "active": {
            "type": "boolean"
        },
        "plants": {
            "type": "array",
            "minimum": 2,
            "items": {
                "type": "object",
                "properties": {
                    "plantname": {
                        "type": "string",
                        "pattern": "\\w[ ]?\\w"
                    },
                    "leaf": {
                        "type": "integer"
                    },
                    "poisonus": {
                        "type": "boolean"
                    },
                    "category": {
                        "type": "string",
                        "enum": [
                            "a",
                            "b",
                            "c"
                        ]
                    }
                }
            },
            "required": [
                "plantname",
                "leaf",
                "posonus",
                "category"
            ]
        }
    },
    "required": [
        "name",
        "population",
        "active",
        "plants"
    ],
    "additionalProperties": true
}

=== Amitpatil215/JIIT-SEM-6/CloudBasedEnterpriseSystem/T2_practice/spacestation.json
{
    "$schema": "./spacestation_schema.json",
    "name": "Telsa Space",
    "population": 6,
    "active": true,
    "plants": [
        {
            "plantname": "Green Plant",
            "leaf": 5,
            "poisonus": false,
            "category": "b"
        },
        {
            "plantname": "Small yeeloow",
            "leaf": 2,
            "poisonus": true,
            "category": "b"
        }
    ]
}
